import React, { useEffect, useState } from 'react';

import Head from 'next/head';
import { store } from 'react-notifications-component';
import { useDispatch } from 'react-redux';

import { GoogleApp } from 'components/GoogleMap';
import { useDebounce } from 'hooks';
import { searchDataSaga } from 'store/actions/searchData';
// import { storeTypes } from 'types/store';
import { APP_NAME, DANGER } from 'utils/constants/notifyTypes';
import { getToaster } from 'utils/helpers/toast';

const Home = () => {
    const dispatch = useDispatch();
    // const { searchDataState } = useSelector((state: storeTypes.IStore) => state);

    const [searchWord, setSearchWord] = useState<string>('');

    const debouncedSearchTerm = useDebounce(searchWord, 1000);

    const [currentLat, setCurrentLat] = useState<number | null>(null);
    const [currentLang, setCurrentLang] = useState<number | null>(null);

    useEffect(() => {
        if (navigator && navigator.permissions) {
            navigator.permissions.query({ name: 'geolocation' }).then((result) => {
                if (result.state === 'granted') {
                    getCurrentLocation();
                } else if (result.state === 'prompt') {
                    getCurrentLocation();
                } else if (result.state === 'denied') {
                    store.addNotification(getToaster(`${APP_NAME} Location`, 'Permission denied', DANGER));
                }
            });
        } else {
            store.addNotification(getToaster(`${APP_NAME} Location`, 'Permission denied', DANGER));
        }
    }, []);

    const getCurrentLocation = () => {
        if (navigator.geolocation) {
            navigator.geolocation.watchPosition((position) => {
                setCurrentLat(position.coords.latitude);
                setCurrentLang(position.coords.longitude);
            });
        }
    };

    useEffect(() => {
        if (debouncedSearchTerm) {
            const payload = {
                search: searchWord,
                km: 10,
                lat: currentLat,
                lang: currentLang
            };
            dispatch(searchDataSaga(payload));
        }
    }, [currentLang, currentLat, debouncedSearchTerm, dispatch, searchWord]);

    return (
        <>
            <input type="text" value={searchWord} onChange={(e) => setSearchWord(e.target.value)} />
            <Head>
                <title>App Name</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="container-fluid">
                <GoogleApp />
            </div>
        </>
    );
};

export default Home;
