import React from 'react';

import Head from 'next/head';

const Home = () => {
    return (
        <>
            <Head>
                <title>App Name</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="container-fluid">Test</div>
        </>
    );
};

export default Home;
